name: FromDoppler

on:
  workflow_dispatch:
  push:
    branches: [main, master, develop]
  pull_request:
    branches: [main, master, develop]

jobs:
  conventional-commits:
    if: |
      github.event_name == 'workflow_dispatch' ||
      github.event_name == 'push' ||
      (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'renovate/'))
    name: Conventions
    uses: FromDoppler/.github/.github/workflows/conventions.yml@main
